cellpose:
  cellprob_threshold: 0.35
  channels:
  - 1
  - 1
  diameter: 0
  flow_threshold: 0.5
  gpu: true
  model_type: cyto2
data:
  input_dir: "./input_images/Green_Maxt0_255"
  output_dir: "./output_segmentations"
  pattern: "Maxt0_00_*.jpg"
  ground_truth_dir: "./ground_truth"
preprocessing:
  channel_index: 1
  invert_intensity: false
  scale_to_01: false
  use_single_channel: true
segmentation:
  save_composite: true
  save_masks: true
  save_outlines: true
  save_flows: true