cellpose:
  cellprob_threshold: 0.3          # Menor umbral = más detección (aunque con más falsos positivos)
  channels:
  - 2                              # Canal azul (donde está la señal real)
  - 0                              # Segundo canal 0 = None
  diameter: 0                     
  flow_threshold: 0.5              
  gpu: true
  model_type: cyto2                
data:
  ground_truth_dir: "./ground_truth"
  input_dir: "./input_images"
  output_dir: "./output_segmentations"
  pattern: "Maxt0_*_*.jpg"     
preprocessing:
  channel_index: 2                 # Usa canal azul
  invert_intensity: false         # No invertir
  scale_to_01: true               # Normaliza a [0,1]
  use_single_channel: true
segmentation:
  save_composite: true
  save_masks: true
  save_outlines: true
  save_flows: true