cellpose:
  cellprob_threshold: -1.0
  channels:
  - 0
  - 0
  diameter: 120
  flow_threshold: 0.8
  gpu: true
  model_type: nuclei
data:
  input_dir: ./input_images/Green_Maxt0_255
  output_dir: ./output_segmentations
  pattern: Maxt0_*_*.jpg
preprocessing:
  channel_index: 1
  invert_intensity: false
  scale_to_01: true
  use_single_channel: true
segmentation:
  save_composite: true
  save_masks: true
  save_outlines: true
